# HTTP -> HTTPS
server {
    listen 80;
    server_name fuelstock.com.br www.fuelstock.com.br;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}


# HTTPS
server {
    listen 443 ssl;
    server_name fuelstock.com.br www.fuelstock.com.br;

    root /usr/share/nginx/html;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/fuelstock.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/fuelstock.com.br/privkey.pem;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location /api/ {
        proxy_pass http://backend:3000/;
    }
    
    location / {
        try_files $uri $uri/ /index.html;
    }
}